/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package compsciia;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.awt.Color;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset; 

/**
 *
 * @author zaida
 */
public class GameDeveloper extends javax.swing.JFrame {
    
    /**
     * Creates new form Try
     */
    public GameDeveloper() {
        initComponents();
    } 
    String team1; String team2; 
    String team3; String team4;
    int scoreOne = 0; int scoreTwo = 0; 
    int scoreThree = 0; int scoreFour = 0;
    int currentgoal=0; 

List<Player> players = new ArrayList<>();
fileRW fileRW = new fileRW();
    
    private int findPlayerIndex(String str){
        int index = -1;
        String pnumber = str.split(",")[2];
        Iterator<Player> iterator = players.iterator();
        while(iterator.hasNext()){
            Player p = iterator.next();
            if(p.pnumber.equals(pnumber)){
                index = players.indexOf(p);
            }
        }
        return index;
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        list1 = new java.awt.List();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        list9 = new java.awt.List();
        jButton6 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        list2 = new java.awt.List();
        list3 = new java.awt.List();
        jLabel4 = new javax.swing.JLabel();
        list4 = new java.awt.List();
        list5 = new java.awt.List();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        list8 = new java.awt.List();
        list10 = new java.awt.List();
        jButton8 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        list6 = new java.awt.List();
        list7 = new java.awt.List();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        list12 = new java.awt.List();
        jLabel9 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(204, 204, 255));

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        jButton1.setText("Save and Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        list1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Players");

        jLabel2.setText("Goals");

        jButton3.setText("Add Player");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });

        jButton4.setText("Remove Player");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("+");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        list9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list9ActionPerformed(evt);
            }
        });

        jButton6.setText("Previous Data");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jButton6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(list9, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(203, 203, 203)
                        .addComponent(jLabel2)
                        .addGap(81, 81, 81))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(42, 42, 42))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addGap(28, 28, 28))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1))
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(list9, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4))
                    .addComponent(list1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Player Data", jPanel1);

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));

        jButton10.setText("Form Team");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel3.setText("GAME 1");

        list2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list2ActionPerformed(evt);
            }
        });

        list3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list3ActionPerformed(evt);
            }
        });

        jLabel4.setText("GAME 2");

        list4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list4ActionPerformed(evt);
            }
        });

        list5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list5ActionPerformed(evt);
            }
        });

        jLabel5.setText("Team 1");

        jLabel6.setText("Team 2");

        jLabel7.setText("Team 3");

        jLabel8.setText("Team 4");

        jButton12.setText("Reset");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton14.setText("Save and Close");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton7.setText("GAME 1 SCORE");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        list8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list8ActionPerformed(evt);
            }
        });

        list10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list10ActionPerformed(evt);
            }
        });

        jButton8.setText("GAME 2 SCORE");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(jLabel5)
                .addGap(54, 54, 54)
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton10)
                        .addGap(47, 47, 47)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(list8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(list2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(list3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(jButton7))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(list4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(37, 37, 37)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel8))
                            .addComponent(list5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(112, 112, 112))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(list10, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton8)
                        .addGap(131, 131, 131))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(181, 181, 181))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton12)
                .addGap(18, 18, 18)
                .addComponent(jButton14)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(list2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton10)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(list5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(list4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(list3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(list10, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(list8, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton12)
                    .addComponent(jButton14))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Team & Scoreboard", jPanel2);

        jPanel3.setBackground(new java.awt.Color(204, 153, 255));

        jLabel12.setText("EXTRA PLAYERS");

        list6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list6ActionPerformed(evt);
            }
        });

        list7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list7ActionPerformed(evt);
            }
        });

        jLabel13.setText("PLAYERS");

        jLabel14.setText("GAMES PLAYED");

        jButton13.setText("Reset");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton15.setText("Save and Close");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setText("GAMES");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        list12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list12ActionPerformed(evt);
            }
        });

        jLabel9.setText("CURRENT PLAYER GOALS");

        jButton9.setText("Bar Chart of Best Players");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel13)
                                .addGap(147, 147, 147)
                                .addComponent(jLabel14))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(list6, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(153, 153, 153)
                                .addComponent(jButton16)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(list7, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(48, 48, 48)))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(list12, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton15)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(list12, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                            .addComponent(list7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton16)
                        .addGap(358, 358, 358)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton13)
                    .addComponent(jButton15)
                    .addComponent(jButton9))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(list6, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Game Statistics", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        fileRW.save(players);
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        players.clear();
        list1.clear();
        list3.setBackground(Color.white);list2.setBackground(Color.white);
        list4.setBackground(Color.white);list5.setBackground(Color.white);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void list1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list1ActionPerformed
       
    }//GEN-LAST:event_list1ActionPerformed
   
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        String lastname = input("Enter Player's Last Name:") ;
        if(lastname.length()<1){
            GameDeveloper.infoBox("This must be longer than one letter.", "!");
            lastname = input("Enter Player's Last Name:") ;
        }
        String name = input("Enter Player's Name:") ;
        if(name.length()<1){
            GameDeveloper.infoBox("This must be longer than one letter.", "!");
            name = input("Enter Player's Name:") ;
        }
        String pnumber = input("Enter Player's Number:");
        if(pnumber.length()<1){
            GameDeveloper.infoBox("Please enter a number.", "!");
            pnumber = input("Enter Player's Number:");
        }
        String playerinfo = lastname + ',' + name + ',' + pnumber + ", Total Goals: 0" ;
        players.add(new Player(lastname, name, pnumber, 0, 0, 0));
        list1.add(playerinfo);
        
    }//GEN-LAST:event_jButton3ActionPerformed
   
    public void bSort(){
        Player cur;
        if (players.size()>1){
         for (int i=0; i<players.size(); i++){
            for (int z=0; z < players.size()-i-1; z++) {
              if (players.get(z).compareTo(players.get(z+1)) > 0){
                cur = players.get(z);
                players.set(z,players.get(z+1) );
                players.set(z+1, cur);
                    }
                }
            }
        }   
    }
        
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       try{
        int selectedIndex = findPlayerIndex(list1.getSelectedItem());
        Player z = players.get(selectedIndex);
        players.remove(z);
        list1.remove(list1.getSelectedItem());
       }
       catch(NullPointerException e){
            GameDeveloper.infoBox("Please select a player first!", "!");
       }
    }//GEN-LAST:event_jButton4ActionPerformed
      public static void infoBox(String infoMessage, String titleBar )
    {  
        JOptionPane.showMessageDialog(null, infoMessage, "ERROR " + titleBar, JOptionPane.INFORMATION_MESSAGE);
    }

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try{
        list12.removeAll();
        int selectedIndex = findPlayerIndex(list1.getSelectedItem());
       
        Player z = players.get(selectedIndex);
        z.goals = z.goals + 1;
        z.currentgoal = z.currentgoal +1; 
        players.set(selectedIndex, z);
        bSort();
        list1.removeAll();
        Iterator<Player> iterator = players.iterator();
        while(iterator.hasNext()){
            Player p = iterator.next();       
            String lastname = p.lastname;
            String name = p.name;
            String pnumber = p.pnumber;
            int goals = p.goals;
            currentgoal = p.currentgoal;
            String alldata = lastname + ',' + name + ',' + pnumber + ", Total Goals: "  + goals ;
            list1.add(alldata);
            String cc = name + ", score: " + currentgoal ;
            list12.add(cc);
            }
        }
        catch(NullPointerException e){
             GameDeveloper.infoBox("Please select a player first!", "!");
        }
    }//GEN-LAST:event_jButton5ActionPerformed
    
    List<Player> teamOne = new ArrayList<>(); //complex 3 :list and itertor
    List<Player> teamTwo = new ArrayList<>();
    List<Player> teamThree = new ArrayList<>();
    List<Player> teamFour = new ArrayList<>();
    List<Player> extraplayers = new ArrayList<>();
    List<Player> lastplayer = new ArrayList<>();

     
    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        list2.removeAll(); teamOne.clear();   //seperate game , when new game start score in 0 
        list3.removeAll(); teamTwo.clear(); currentgoal=0; 
        list4.removeAll(); teamThree.clear();
        list5.removeAll(); teamFour.clear();
        list7.removeAll(); list12.removeAll(); 
        list3.setBackground(Color.white);list2.setBackground(Color.white);
        list4.setBackground(Color.white);list5.setBackground(Color.white);
     
        if(players.size()<=1){
        GameDeveloper.infoBox("You must have more than one player.", "!");
        }
        
        Iterator<Player> iter = players.iterator();
     while(iter.hasNext()){
         Player q = iter.next();
         q.currentgoal=0; 
     }
     
     if(!extraplayers.isEmpty()){
     Iterator<Player> iteratorexp = extraplayers.iterator();
     while(iteratorexp.hasNext()){
         Player p = iteratorexp.next();
         players.remove(p);
         players.add(0,p);   
     }
     extraplayers.clear();
     }
    
     if(extraplayers.isEmpty()){  
         if(!lastplayer.isEmpty()){
         Iterator<Player> iteratorlast = lastplayer.iterator();
         while(iteratorlast.hasNext()){
         Player p = iteratorlast.next();
         players.remove(p);
         players.add(0,p);   
     }
         }   
     lastplayer.clear();
     }
        
      //process of distributing equal amount of players
     Iterator<Player> iterator = players.iterator();
     while(iterator.hasNext()){
         if(iterator.hasNext()){teamOne.add(iterator.next()); }
         if(iterator.hasNext()){teamTwo.add(iterator.next());}
         if(iterator.hasNext()){teamThree.add(iterator.next());}
         if(iterator.hasNext()){teamFour.add(iterator.next());}  
     }
     if(players.size()%2!=0){ 
         if(teamOne.size()!=teamTwo.size()){
             extraplayers.add(teamOne.get(teamOne.size()-1));
             teamOne.remove(teamOne.size()-1);
         }
         if(teamThree.size()!=teamFour.size()){
             extraplayers.add(teamThree.get(teamThree.size()-1));
             teamThree.remove(teamThree.size()-1);
         }
     }
     
     Iterator<Player> teamOnePlayers =  teamOne.iterator();
      while(teamOnePlayers.hasNext()){
          Player p = teamOnePlayers.next();
          list2.add(p.name);
          gameCount(p);
      }
      Iterator<Player> teamTwoPlayers =  teamTwo.iterator();
      while(teamTwoPlayers.hasNext()){
          Player p = teamTwoPlayers.next();
          list3.add(p.name);
          gameCount(p);
      }
      Iterator<Player> teamThreePlayers =  teamThree.iterator();
      while(teamThreePlayers.hasNext()){
          Player p = teamThreePlayers.next();
          list4.add(p.name);
          gameCount(p);
      }
      Iterator<Player> teamFourPlayers =  teamFour.iterator();
      while(teamFourPlayers.hasNext()){
          Player p = teamFourPlayers.next();
          list5.add(p.name);
          gameCount(p);
          lastplayer.add(teamFour.get(teamFour.size()-1));
      }
      Iterator<Player> extraiterator = extraplayers.iterator();
      while(extraiterator.hasNext()){
          list7.add(extraiterator.next().name);
      }     
              
    }//GEN-LAST:event_jButton10ActionPerformed
    
    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        list2.clear(); teamOne.clear();
        list3.clear(); teamTwo.clear();
        list4.clear(); teamThree.clear();
        list5.clear(); teamFour.clear();
        list8.clear(); list10.clear();
        list3.setBackground(Color.white);list2.setBackground(Color.white);
        list4.setBackground(Color.white);list5.setBackground(Color.white);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
       list6.clear();  list7.clear(); 
       list3.setBackground(Color.white);list2.setBackground(Color.white);
       list4.setBackground(Color.white);list5.setBackground(Color.white);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        fileRW.save(players);
        System.exit(0);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        fileRW.save(players);
        System.exit(0);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void list6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list6ActionPerformed
       
    }//GEN-LAST:event_list6ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        list6.removeAll(); //clears GUI list
        Iterator<Player> iterator = players.iterator();
        while(iterator.hasNext()){
            Player p = iterator.next();
            String msg = "";
            msg = msg + p.name + ":    Games:" + p.games + "\n";
            list6.add(msg);
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    public void gameCount(Player x){
        x.games = x.games + 1; //when method is called game count increases
        
    }
    
    private void jButton3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3KeyPressed

    private void list2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_list2ActionPerformed

    private void list3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_list3ActionPerformed

    private void list4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_list4ActionPerformed

    private void list5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_list5ActionPerformed

    private void list9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_list9ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       List<Player> previousPlayers = fileRW.load();
       Iterator<Player> iterator = previousPlayers.iterator();
      while(iterator.hasNext()){
        Player p = iterator.next();
        String lastName = p.lastname;
        String name = p.name;
        String pnumber = p.pnumber;
        int numberofgoals = p.goals;
        list9.add(lastName + ", " + name + ", "+pnumber + ", " + numberofgoals);
      }
       
    }//GEN-LAST:event_jButton6ActionPerformed
   
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
    list8.clear();
    list3.setBackground(Color.white);list2.setBackground(Color.white);
    scoreOne = 0;
    Iterator<Player> iteratorOne = teamOne.iterator();
    while(iteratorOne.hasNext()){
    Player w = iteratorOne.next();
    scoreOne += w.currentgoal;
    }
    scoreTwo = 0;
    Iterator<Player> iteratorTwo = teamTwo.iterator();
    while(iteratorTwo.hasNext()){
    Player q = iteratorTwo.next();
    scoreTwo += q.currentgoal;
    }
    list8.add(scoreOne + " : " + scoreTwo);
    if (scoreOne>scoreTwo){
        list2.setBackground(Color.green);
    }
    else if(scoreOne<scoreTwo){
        list3.setBackground(Color.green);
    }
    else if(scoreOne==scoreTwo){
        list3.setBackground(Color.yellow);
        list2.setBackground(Color.yellow);
    }
    else{
        list3.setBackground(Color.white);list2.setBackground(Color.white);
    }
    
    
    }//GEN-LAST:event_jButton7ActionPerformed
    
    private void list8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_list8ActionPerformed

    private void list7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_list7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
    list10.clear();
    list4.setBackground(Color.white);list5.setBackground(Color.white);
    scoreThree = 0;
    Iterator<Player> iteratorThree = teamThree.iterator();
    while(iteratorThree.hasNext()){
    Player w = iteratorThree.next();
    scoreThree += w.currentgoal;
    }
    scoreFour = 0;
    Iterator<Player> iteratorFour = teamFour.iterator();
    while(iteratorFour.hasNext()){
    Player q = iteratorFour.next();
    scoreFour += q.currentgoal;
    }
    list10.add(scoreThree + ":" + scoreFour);
     if (scoreThree>scoreFour){
        list4.setBackground(Color.green);
    }
    else if(scoreThree<scoreFour){
        list5.setBackground(Color.green);
    }
    else if(scoreThree==scoreFour){
        list4.setBackground(Color.yellow);
        list5.setBackground(Color.yellow);
    }
    else{
        list4.setBackground(Color.white);list5.setBackground(Color.white);
    }
    
                    
    }//GEN-LAST:event_jButton8ActionPerformed

    private void list10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_list10ActionPerformed

    private void list12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_list12ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        int bestP; String b; 
        int secbest;  String s;
        int thirdbest; String t;
       
    try{
       Player e= players.get(players.size()-1);
       bestP = e.goals;
       b = e.name; 
       Player d = players.get(players.size()-2);
       secbest = d.goals;
       s = d.name;
       Player f = players.get(players.size()-3);
       thirdbest = f.goals;
       t = f.name;
       
        DefaultCategoryDataset pData = new DefaultCategoryDataset();  
        pData.setValue(bestP, "Best Player", b);
        pData.setValue(secbest, "Second Best Player", s);
        pData.setValue(thirdbest, "Thrid Best Player", t);
        JFreeChart chart =  ChartFactory.createBarChart("Top Players", "Players", "Goals", pData, PlotOrientation.VERTICAL, true, true, false);
        CategoryPlot c = chart.getCategoryPlot();
        c.setRangeGridlinePaint(Color.gray);
        ChartFrame frame = new ChartFrame("Bar Graph", chart);
        frame.setVisible(true);
        frame.setSize(450, 350);}
       
    catch(ArrayIndexOutOfBoundsException e){
           GameDeveloper.infoBox("There must be more than three players.", "!");
       }
            
    }//GEN-LAST:event_jButton9ActionPerformed
    
    /**
     * @param args the command line arguments
     *
     */
    public static void main(String args[])  {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameDeveloper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameDeveloper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameDeveloper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameDeveloper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GameDeveloper().setVisible(true);
        });
    }

 public String input(String prompt)
   { 
       javax.swing.JTextField tf = new javax.swing.JTextField(16);
       tf.setFont(tf.getFont().deriveFont(24f));
       int result = javax.swing.JOptionPane.showConfirmDialog(null, tf, prompt, javax.swing.JOptionPane.DEFAULT_OPTION);
      return tf.getText(); 
   }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private java.awt.List list1;
    private java.awt.List list10;
    private java.awt.List list12;
    private java.awt.List list2;
    private java.awt.List list3;
    private java.awt.List list4;
    private java.awt.List list5;
    private java.awt.List list6;
    private java.awt.List list7;
    private java.awt.List list8;
    private java.awt.List list9;
    // End of variables declaration//GEN-END:variables
}